version: 2
jobs:
  build-and-test:
    working_directory: ~/sbpractice
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
        
  two:
    working_directory: ~/reactjs
#       steps:
#       - checkout
#       - run:
      - node/test
        version: '15.1
workflows:
    jobs:
      - build-and-test
      - two:
          requires:
            - build-and-test
