# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run


# version: 2
# jobs:
#   build-and-test:
#     working_directory: ~/sbpractice
#     steps:
#       - checkout
#       - run:
#           name: Build
#           command: mvn -B -DskipTests clean package
#       - run:
#           name: Test
#           command: mvn test
        
#   two:
#     working_directory: ~/reactjs
# #       steps:
# #       - checkout
# #       - run:
#       - node/test
#         version: '15.1
# workflows:
#     jobs:
#       - build-and-test
#       - two:
#           requires:
#             - build-and-test
